python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_0.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_1.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_2.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_3.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_4.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_5.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_6.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_7.json
python train_geo_stage2_colmap.py  --config configs/ihpc/mip_kitchen_8.json